In [12]:
import numpy as np

statdist = np.asarray([0.25, 0.5, 0.25])
P = np.random.rand(3,3)
P = P / (P.sum(axis=1))
print(statdist)
print(P)
data = (np.random.rand(100)-0.5)*20
print(data)

[ 0.25  0.5   0.25]
[[ 0.46605773  0.14097437  0.27661854]
 [ 0.18341151  0.2024939   0.48528101]
 [ 0.22002667  0.50950976  0.44629882]]
[ 5.82744795  1.77114781  5.32214214 -5.34466007  2.10540255 -9.26167479
  2.16074565  4.87109213 -9.58788221 -0.09262658 -5.22794522 -4.36783987
  9.73905421 -3.65315645 -5.73602773  6.83358104  0.05245177  5.89059099
 -1.23063563  1.77318265 -2.93358724  1.71221125  2.24237932 -7.92196193
 -2.14949353 -5.75466454 -6.3952922  -9.93601464  4.279011   -3.34096658
 -8.10592526 -8.05320654 -4.90739301 -2.46451975 -7.65444253  0.15905404
 -6.85563356 -1.87929376 -7.14801012  9.91070908  5.07901189  9.92885152
 -2.27629226 -2.22480329  4.32869902  6.33294344 -3.30363368  7.51100965
  4.87167058 -3.42524825  5.81331637  3.8705107  -7.76914677 -8.42803812
 -3.03868467 -1.18261074  4.15925317  0.08627995 -2.57683461 -6.19390984
  8.41967963 -0.29348552  7.17550607  6.97644996 -4.65569839  0.516095
  6.38758888  0.33466211  2.86588779  7.3095327  -8.1387229  

In [17]:
sample = np.random.choice(range(data.shape[0]), 1000)
print(sample)

[ 8 78 49 95  3 99 81  5 64 50 56 60  3  8 55 17 92 57 81 75 38 84 93 13 53
 31 18 68 81 19  7 92 21 84 71 55  7 92 71 44 69 68 74 11 47 34 80 74 79 51
 81 18 92 23 91 90 82 46  2 55 22 56 21 73 39 48 15 83  8 54 96 82 99 31 85
  1 74 19 43 68 99 34 62 38 21 22 72 49 83  2 70 73 74 13 41 81 96 80 91 32
 85 43  7 34 96 46 27 82 99 34 64  9 21 41 56  8 67 97 78 65 23  8 48 14 80
 64 10 84 63 22 86  8 54 72 44 59  4 52 69 60 44  9 38 27  8 21 55  1 39 50
 52 99 23 86 36 49 45 99 17 52  0 38 14 12 86 69  7 85 80  1  4 89 52 48 81
 64 31 32 61 70 42 12 41 41 46  0 84 63 94 67  1 38 57 97 91 44  9 59 14 68
 13 72  1 60 31 41 90  7 10 99 64 18 18  9 77 60 64 60 50 11 54 75 80 46 56
 54 26 54 33 70 89  0 85 40  7 63 62 49 97 33 70 74 38 69 69 92 17 76 87 40
 66 21 83 32 31 23 41 47 50 72 48 31 95 60 65 17 32 93 53 88  4 16 15 77  8
 35 49 28 80 34 37 82 68  8 21 59 98 43 43 62 74 84 82 13 98 37 83 82 71 85
 43 45 50 20 39 21 30  7 65 15 59 68  1 93 12 69 11 66 12 86 63  4 49 99 40
  1 45  2 30

In [18]:
chosenValues = data[sample]
print(chosenValues)

[-9.58788221  4.94461636 -3.42524825 -5.34472142 -5.34466007 -6.02074504
  4.74091925 -9.26167479 -4.65569839  5.81331637  4.15925317  8.41967963
 -5.34466007 -9.58788221 -1.18261074  5.89059099  3.96940295  0.08627995
  4.74091925 -8.29442003 -7.14801012  0.12652655  0.69715829 -3.65315645
 -8.42803812 -8.05320654 -1.23063563  2.86588779  4.74091925  1.77318265
  4.87109213  3.96940295  1.71221125  0.12652655 -8.87601744 -1.18261074
  4.87109213  3.96940295 -8.87601744  4.32869902  7.3095327   2.86588779
  9.93550918 -4.36783987  7.51100965 -7.65444253  6.61951565  9.93550918
  2.88224134  3.8705107   4.74091925 -1.23063563  3.96940295 -7.92196193
  7.68715898 -6.20185163 -3.18230184 -3.30363368  5.32214214 -1.18261074
  2.24237932  4.15925317  1.71221125 -8.15873057  9.91070908  4.87167058
  6.83358104  7.43021003 -9.58788221 -3.03868467 -5.25421282 -3.18230184
 -6.02074504 -8.05320654 -9.14865319  1.77114781  9.93550918  1.77318265
 -2.22480329  2.86588779 -6.02074504 -7.65444253  7