In [1]:
import numpy as np
import random

# oh so pretty!
def float_formatter(x):
    if x < 0.001 and x > 0:
        return "   >0" 
    elif x == 0:
        return "    0" 
    else:
        return "%.3f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})

A = np.random.rand(500,500)
A = A/A.sum(axis=1)[:,None]
print(A.sum(axis=1))

E = np.random.rand(500, 4)
E = E / E.sum(axis=1)[:,None]
print(E.sum(axis=1))
pi = np.random.rand(500)
pi = pi/pi.sum()
print(pi.sum())

#ACGT
def l2i(l):
    d = {'A':0, 'C':1, 'G':2, 'T':3}
    return d[l]

print(l2i('A'))

[1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.

In [2]:
# define all possible outcomes of all states:
outcomes_dict = {} # ohh gawd this is akward
outcomes = np.empty([20], dtype=object) # help me, im lost
i = 0
letters = 'ACGT'
for letter1 in letters:
    outcomes[i] = letter1
    outcomes_dict[letter1] = i
    i += 1
    for letter2 in letters:
        outcomes[i] = letter1 + letter2# + letter3
        #outcomes_dict[letter1 + letter2 + letter3] = i
        outcomes_dict[letter1 + letter2] = i
        i += 1

            
#outcomes_dict = alphabet
#outcomes=np.asarray(('A', 'C', 'G', 'T'))
#ACGT
def l2i(l):
    if type(l) is str:
        if l == "":
            return -1
        else:
            return outcomes_dict[l]
    else:
        return [l2i(l_) for l_ in l]
#i can either be a list of indices, or just an index
def i2l(i):
    if type(i) is int:
        return outcomes[i]
    else:
        return [outcomes[i_] for i_ in i]
def e_prop(E, s):
    result = list()
    for i in range(len(s)):
        if i < 0:
            result.append(-1)
        else:
            result.append(E[i, s[i]])
    return result
    
print(outcomes)

['A' 'AA' 'AC' 'AG' 'AT' 'C' 'CA' 'CC' 'CG' 'CT' 'G' 'GA' 'GC' 'GG' 'GT'
 'T' 'TA' 'TC' 'TG' 'TT']


In [3]:
#Here we make some test data, to see if viterbi works.

A = np.zeros((3,3))
E = np.zeros((3,outcomes.shape[0]))
pi = np.zeros(3)
A[0, 1] = 0.2
A[0, 2] = 0.2

A[1, 0] = 0.75
A[1, 2] = 0.25
A[2, 0] = 0.75
A[2, 1] = 0.25

E[0, 1] = 0.333 #AA
E[0, 2] = 0.333 #AC
E[0, 3] = 0.333 #AG
E[0, 4] = 0.333 #AT
E[1, 5] = 0.7 #C
E[1, 10] = 0.2 #G
E[1,15] = 0.1 #T
E[2, 5] = 0.2 #C
E[2, 10] = 0.7 #G
E[2 ,15] = 0.1 #T

pi[:] = 1/3

q = np.ones(3, dtype=np.int32)
q[0] = 2
print(A)
print()
print(E)
print()
print(pi)
print()
print(q)

[[    0 0.200 0.200]
 [0.750     0 0.250]
 [0.750 0.250     0]]

[[    0 0.333 0.333 0.333 0.333     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]
 [    0     0     0     0     0 0.700     0     0     0     0 0.200     0
      0     0     0 0.100     0     0     0     0]
 [    0     0     0     0     0 0.200     0     0     0     0 0.700     0
      0     0     0 0.100     0     0     0     0]]

[0.333 0.333 0.333]

[2 1 1]


In [4]:
s_ = "abcde"
s = np.chararray(len(s_), unicode=True)
s[:] = list(s_)
v = np.ones(3, dtype=np.int32)
v[0] = 3
v[1] = 4
v[2] = 1
print(s[2:3])
print(s)
print(s[0])
print(v)
print(s[v])
v[None]

['c']
['a' 'b' 'c' 'd' 'e']
a
[3 4 1]
['d' 'e' 'b']


array([[3, 4, 1]])

In [5]:
#Calculates the path with maximum likelihood for string s.
#A is transmissions, E is emissions and p is pi

def viterbi_gen(A, E, p, s):
    result = -1*np.ones([A.shape[0], len(s)])
    result[:, 0] = E[:, alphabet[s[0]]]*p
    for i in range(1, len(s)):
        if i % 100 == 0:
            print("\r" + str(i), end="")
        a =  (A.T * result[:, i-1]).max(axis=1)
        b = a * E[:, alphabet[s[i]]]
        result[:, i] = b
    return result

def viterbi_path(X, A, E, p, s):
    n = X.shape[1]-1
    path = np.zeros(n+1, dtype=np.int32)
    path[n] = np.argmax(X[:, n], axis=0)
    for i in range(n-1, -1, -1):
        p = E[path[i+1], alphabet[s[i+1]]]
        p = p * X[:, i]
        p = p * A[:, path[i+1]]
        path[i] = np.argmax(p)
    return path

def viterbi(A, E, p, s):
    X = viterbi_gen(A, E, p, s)
    return viterbi_path(X, A, E, p, s)

In [6]:
print(viterbi(A, E, pi, "ACGTTG"))

NameError: name 'alphabet' is not defined

In [49]:
#This is the Viterbi algorithm, where different states, can take input of different length.
#A, E, p and s is as above. q is a vector, signifying the length of inputs for each state.

s = "AAGATCGTAATC"

def viterbi_ext_gen(A, E, p, s, q):
    #We convert the input string to a numpy char-array
    s_ = np.chararray(len(s), unicode=True)
    s_[:] = list(s)
    s = s_
    #Then we generate some result matrix, with -1 everywhere.
    result = -1*np.ones([A.shape[0], len(s)])
    #We save how long we have gotten in each "row"
    step = np.zeros(A.shape[0], dtype=np.int32)
    #We store the first row, to know the probability of starting in each state.
    s_ = l2i(["".join(s[0: q_]) for q_ in q])
    result[:, 0] = e_prop(E, s_)*p
    step = step+q
    for i in range(1, len(s)):
        if i % 100 == 0:
            print("\r" + str(i), end="")
        #First we calculate the argument of the ealier state max probability.
        arg =  (A.T * result[:, i-1]).argmax(axis=1)
        #Then we calculate the actual max
        m = (A.T * result[:, i-1]).max(axis=1)
        #Then we calculate the emission probability
        step_ = step[arg]
        s_ = ["".join(s[step_[i]:step_[i]+q[i]]) for i in range(len(step))]
        s_ = l2i(s_)
        e = [E[i, s_[i]] for i in range(len(s_))]
        #Then we fill in the actual probabilities
        result[:, i] = m*e
        step = step_ + q
        highest = np.argmax(result[:, i])
        if step[highest] >= len(s):
            result = result[:, :i+1]
            break
    return result

def viterbi_ext_path(X, A, E, p, s, q):
    n = X.shape[1]-1
    j = len(s)
    path = -1*np.ones(n+1, dtype=np.int32)
    path[n] = np.argmax(X[:, n], axis=0)
    for i in range(n, 0, -1):
        q_ = q[path[i]]
        s_ = s[j-q_:j]
        p = E[path[i], l2i(s_)]
        p = p * X[:, i-1]
        p = p * A[:, path[i]]
        path[i-1] = np.argmax(p)
        j = j-q_
    return path

X = viterbi_ext_gen(A, E, pi, s, q)
print(X)
viterbi_ext_path(X, A, E, pi, s, q)

[[0.111     0 0.004]
 [    0 0.004     0]
 [    0 0.016     0]]


array([0, 2, 0])