In [1]:
import numpy as np
import random

# oh so pretty!
def float_formatter(x):
    if x < 0.001 and x > 0:
        return "   >0" 
    elif x == 0:
        return "    0" 
    else:
        return "%.3f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})

A = np.random.rand(500,500)
A = A/A.sum(axis=1)[:,None]
print(A.sum(axis=1))

E = np.random.rand(500, 4)
E = E / E.sum(axis=1)[:,None]
print(E.sum(axis=1))
pi = np.random.rand(500)
pi = pi/pi.sum()
print(pi.sum())

#ACGT
def l2i(l):
    d = {'A':0, 'C':1, 'G':2, 'T':3}
    return d[l]

print(l2i('A'))

[1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000
 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.

In [2]:
#Here we make some test data, to see if viterbi works.

A = np.zeros((3,3))
E = np.zeros((3,4))
pi = np.zeros(3)
alphabet={'a':0, 'b':1, 'c': 2, 'd':3}
A[0, 1] = 0.5
A[0, 2] = 0.5
A[1, 0] = 0.75
A[1, 2] = 0.25
A[2, 0] = 0.75
A[2, 1] = 0.25

E[0, 0] = 1
E[1, 1] = 0.7
E[1, 2] = 0.2
E[1,3] = 0.1
E[2, 1] = 0.2
E[2, 2] = 0.7
E[2 ,3] = 0.1

pi[:] = 1/3

print(A)
print()
print(E)
print()
print(pi)


[[    0 0.500 0.500]
 [0.750     0 0.250]
 [0.750 0.250     0]]

[[1.000     0     0     0]
 [    0 0.700 0.200 0.100]
 [    0 0.200 0.700 0.100]]

[0.333 0.333 0.333]


In [ ]:
#ACGT
def l2i(l):
    d = {'A':0, 'C':1, 'G':2, 'T':3}
    return d[l]

In [41]:
#Calculates the path with maximum likelihood for string s.
#A is transmissions, E is emissions and p is pi

def viterbi_gen(A, E, p, s):
    result = -1*np.ones([A.shape[0], len(s)])
    result[:, 0] = E[:, alphabet[s[0]]]*p
    for i in range(1, len(s)):
        if i % 100 == 0:
            print("\r" + str(i), end="")
        a =  (A.T * result[:, i-1]).max(axis=1)
        b = a * E[:, alphabet[s[i]]]
        result[:, i] = b
    return result

def viterbi_path(X, A, E, p, s):
    n = X.shape[1]-1
    path = np.zeros(n+1, dtype=np.int32)
    path[n] = np.argmax(X[:, n], axis=0)
    for i in range(n-1, -1, -1):
        p = E[path[i+1], alphabet[s[i+1]]]
        p = p * X[:, i]
        p = p * A[:, path[i+1]]
        path[i] = np.argmax(p)
    return path

def viterbi(A, E, p, s):
    X = viterbi_gen(A, E, p, s)
    return viterbi_path(X, A, E, p, s)

In [43]:
print(viterbi(A, E, pi, "abdcdc"))

[0 2 1 2 1 2]


In [44]:
def viterbi_ext_gen(A, E, p, s):
    result = -1*np.ones([A.shape[0], len(s)])
    step = np.zeros(A.shape[0])
    
    return result